### ISSUE TITLE
Hiragana/katakana glyphs without Unicode

### ISSUE THREAD

**Issue by mashabow** [schriftgestalt/GlyphsInfo#1]
In `GlyphData.xml`, I found there are some hiragana/katakana glyphs without Unicode; but where do
they come from? What are they intended for?

``` xml
$ cat GlyphData.xml | grep -v unicode | grep kana
        <glyph name="nga-hira" category="Letter" script="kana" description="HIRAGANA LETTER NGA" />
        <glyph name="ngi-hira" category="Letter" script="kana" description="HIRAGANA LETTER NGI" />
        <glyph name="ngu-hira" category="Letter" script="kana" description="HIRAGANA LETTER NGU" />
        <glyph name="kosmall-hira" category="Letter" script="kana" description="HIRAGANA LETTER SMALL KO" />
        <glyph name="tea-hira" category="Letter" script="kana" description="HIRAGANA LETTER TEA" />
        <glyph name="kosmall-kata" category="Letter" script="kana" description="KATAKANA LETTER SMALL KO" />
        <glyph name="tea-kata" category="Letter" script="kana" description="KATAKANA LETTER TEA" />
        <glyph name="tai-kata" category="Letter" script="kana" description="KATAKANA LETTER TAI" />
        <glyph name="ce-kata" category="Letter" script="kana" description="KATAKANA LETTER CE" />
        <glyph name="co-kata" category="Letter" script="kana" description="KATAKANA LETTER CO" />
        <glyph name="pusmall-kata" category="Letter" script="kana" description="KATAKANA LETTER SMALL PU" />
```

Although it seems that some of these glyphs (`nga-hira`, `ngi-hira`, `ngu-hira`, `ce-kata`, and `pusumall-kata`) come from JIS X 0213, they are not enough to support the standard. Please refer to [NamedSequences.txt](http://www.unicode.org/Public/UCD/latest/ucd/NamedSequences.txt) in the Unicode Character Database for this.

In addition, while `tea-hira`, `tea-kata`, `tai-kata` are for `さ゚`, `サ゚`,  `シ゚` respectively ([according to @Tosche](https://twitter.com/Tosche_J/status/713002384541155329)), I think these names should be `tsa-hira`, `tsa-kara`, `tsi-kata` or something, based on their pronunciation.

**Comment by brawer** [comment]
@schriftgestalt, would you accept a pull request for fixing these? For example:

```patch
1c1
< <glyph name="nga-hira" category="Letter" script="kana" description="HIRAGANA LETTER NGA" />
> <glyph name="nga-hira" category="Letter" script="kana" production="uni304B309A" description="HIRAGANA LETTER BIDAKUON NGA" />
```

**Comment by schriftgestalt** [comment]
I just found a response to the first issue (I did send it by mail and that didn't come through)

I don't remember exactly but I think I added them on one point as I needed them in the mapping file for Adobe-Japan1. In the mapping file they are called 'ka_semivoicedcomb-hira' now so I could remove them from the glyphData file.

I’ll update the mapping file from my internal file.
