### ISSUE TITLE
Missing unicode property for 920 glyphs

### ISSUE THREAD

**Issue by brawer** [schriftgestalt/GlyphsInfo#10]
Is it intentional that some glyphs have no `unicode` property in GlyphData.xml? What implications does it have when a glyph has a `production` name that can be converted to Unicode, but no `unicode` property in GlyphData.xml?

In glyphsLib, I’m [generating](https://github.com/googlei18n/glyphsLib/blob/master/Lib/glyphsLib/glyphdata.py#L29) the `unicode` property by parsing the `production` name. This works quite fine, but 920 glyphs currently have no `unicode` property. To exactly match the content of GlyphData.xml, I’m currently putting those 920 glyphs into a `MISSING_UNICODE_STRINGS` set in [glyphdata_generated.py](https://github.com/googlei18n/glyphsLib/blob/master/Lib/glyphsLib/glyphdata_generated.py#L26555). But I’m actually not sure this is really needed; maybe those missing `unicode` attributes are just an unintentional omission from GlyphData.xml?

There’s also a few glyphs that really cannot be encoded in Unicode (see https://github.com/schriftgestalt/GlyphsInfo/issues/3 for an example). But that’s a very small number.

**Comment by schriftgestalt** [comment]
Most of the Indic ones are halfforms or precomposed forms. The production name should represent that. The Georgians are in the process of getting unicodes.

**Comment by graphicore** [comment]
I just came across some  ligatures that have apparently unicodes, but only specified indirectly via the `altNames` attribute (`f_f, f_f_i, f_f_l, longs_t,s_t`):

```xml
	<glyph name="f_f" category="Letter" subCategory="Ligature" script="latin" altNames="uniFB00" description="LATIN SMALL LIGATURE FF" />
	<glyph unicode="FB01" name="fi" category="Letter" subCategory="Ligature" script="latin" description="LATIN SMALL LIGATURE FI" />
	<glyph unicode="FB02" name="fl" category="Letter" subCategory="Ligature" script="latin" description="LATIN SMALL LIGATURE FL" />
	<glyph name="f_f_i" category="Letter" subCategory="Ligature" script="latin" altNames="uniFB03" description="LATIN SMALL LIGATURE FFI" />
	<glyph name="f_f_l" category="Letter" subCategory="Ligature" script="latin" altNames="uniFB04" description="LATIN SMALL LIGATURE FFL" />
	<glyph name="longs_t" category="Letter" subCategory="Ligature" script="latin" altNames="uniFB05" description="LATIN SMALL LIGATURE LONG S T" />
	<glyph name="s_t" category="Letter" subCategory="Ligature" script="latin" altNames="uniFB06" description="LATIN SMALL LIGATURE ST" />
```

Is there a reason for these not having an explicit unicode property or can we add the unicodes?

**Comment by schriftgestalt** [comment]
Those unicodes are deprecated and shouldn't be used any more. Why do you need them?

**Comment by graphicore** [comment]
We actually use them in the google fonts Latin-Plus character set: https://github.com/google/fonts/blob/master/tools/encodings/GF%202016%20Glyph%20Sets/GF-latin-plus_unique-glyphs.nam#L328
Is the deprecation coming from the Unicode standard? Where can I find it? We can probably remove the unicodes from our files, just need to argument it properly.

**Comment by marmouzet** [comment]
It's the general idea of Unicode to give Unicode to letters, not ligatures. If you're looking for a the word "find" in a PDF that is using a Unicode for f_i you won't find it.
Similar problem will happen if you copy-paste a text with f_i Unicode and then use a font that doesn't. That's why it's deprecated.
It was only used for compatibility with older texts and texts that are using it are getting really rare now.
It's 2017 let's move on :)

**Comment by brawer** [comment]
> Why do you need them?

Good point. When I filed this bug, I thought the `unicode` property of GlyphsData.xml would eventually be needed for correctly compiling glyphs files. When converting a glyph to UFO, glyphsLib takes the UFO `unicode` property from the input Glyphs file. But  outside of unit tests, the current glyphsLib code never seems to retrieve the `unicode` property from GlyphsData.xml. So it doesn’t matter — closing bug.
