### ISSUE TITLE
Please add a few missing Arabic Characters from Unicode 9 

### ISSUE THREAD

**Issue by n7s** [schriftgestalt/GlyphsInfo#11]
Hi Georg, 

while working on one of our Arabic fonts, we realized that U+08BB, U+08BC and U+08BD were not shaping as expected (tested with Glyphs 2.4.2 build 1004). I've added them to a local GlyphData.xml file and they work again as intended.  Can you please add the following to the main GlyphData.xml file? 

Thanks!

**Comment by n7s** [comment]
[GlyphData-addition-for-Unicode-9-Aracbic-characters.txt](https://github.com/schriftgestalt/GlyphsInfo/files/885698/GlyphData-addition-for-Unicode-9-Aracbic-characters.txt)

**Comment by schriftgestalt** [comment]
Added it. Thanks
