### ISSUE TITLE
Please add a few missing Arabic Characters from Unicode 10

### ISSUE THREAD

**Issue by n7s** [schriftgestalt/GlyphsInfo#12]
Hi Georg,

Please find attached a few missing glyphs from Unicode 10 to add to the master GlyphsData.xml 

Thanks. 

[glyphsdata-addition-for-Unicode-10-bravanese.txt](https://github.com/schriftgestalt/GlyphsInfo/files/1288159/glyphsdata-addition-for-Unicode-10-bravanese.txt)

**Comment by bobh0303** [comment]
These have been incorporated into GlyphData.xml -- at least they are present in build 1072. Thanks!

For the record, in case someone is looking for them in GlyphData.xml, the glyphnames were modified slightly from the list given by n7s above. In particular, the word "Small" was omitted. Thus:

USV|Proposed name | Name as added
---|--------------|--------------
08B6|behSmallmeemabove-ar|behMeemabove-ar
08B7|pehSmallmeemabove-ar|pehMeemabove-ar
08B8|tehSmalltehabove-ar|tehTehabove-ar
08B9|rehSmallnoonabove-ar|rehNoonabove-ar
08BA|yehTwodotsbelowSmallnoonabove-ar|yehTwodotsbelowNoonabove-ar

**Comment by schriftgestalt** [comment]
I update the public list, soon.
