### ISSUE TITLE
use pkg_resources to manage its XML data files on filter_lists.py

### ISSUE THREAD

**Issue by felipesanches** [schriftgestalt/GlyphsInfo#13]
Please see related issue at: https://github.com/googlefonts/tools/issues/31

**Comment by anthrotype** [comment]
the issue is with your python package which is (incorrectly) including this data files, not with this repository which is data-only and doesn't have anything to do with python packaging.

**Comment by felipesanches** [comment]
oh! That's correct! filter_lists.py is indeed in the other repo. Sorry about the confusion. I'll deal with it there.
