### ISSUE TITLE
Copyright infringement of Adobe AGL

### ISSUE THREAD

**Issue by medicalwei** [schriftgestalt/GlyphsInfo#14]
In the README you stated that the glyphs name are from Adobe AGL, but AGL is a [BSD licensed document][1], therefore modifications should retain the disclaimer and copyright notice according to BSD 3-clause license.

I am doing Debian packaging for the package [glyphsLib][2] which includes a file generated from your repository, but Debian requires files to be built from source.

[1]: https://github.com/adobe-type-tools/agl-aglfn
[2]: https://github.com/googlei18n/glyphsLib

**Comment by schriftgestalt** [comment]
Is the addition to the readme file sufficient?

**Comment by medicalwei** [comment]
I think that's sufficient, though IANAL.

**Comment by anthrotype** [comment]
Since you are packaging this, it would be also helpful to explicitly tag releases so both upstream glyphsLib and its Debian package can refer clearly to the same revision of the data files.
If they were not in sync, they would end up producing different outputs and that’s not good.

**Comment by anthrotype** [comment]
You can just push a git tag from time to time, or even simply create github releases directly from the website, which will also create a git tag for you.

**Comment by anthrotype** [comment]
Or you give me commit access and I can push a tag myself just before I update the glyphsdata embedded in glyphsLib
