### ISSUE TITLE
Aogonek missing anchors?

### ISSUE THREAD

**Issue by davelab6** [schriftgestalt/GlyphsInfo#16]
In a recent project for me, @colophon-foundry had to add in an anchor manually for the Aogonek - it wasn't automatically added as expected, suggesting its missing from the default `GlyphsData.xml`

**Comment by schriftgestalt** [comment]
Why do you need an anchor in the Aogonek?

**Comment by davelab6** [comment]
To prevent mis-rendering the character.

**Comment by moyogo** [comment]
@schriftgestalt If Aogonek is not composed of A+ogonekcomb but has its own outline, then it has no anchors when "Glyph > Set Anchors" or with anchor propagation at build time.
The same applies to other glyphs in particular those with ogonek or cedilla.

**Comment by schriftgestalt** [comment]
So what anchors would be needed and in what contexts?

Are there any cases where there would another mark below? So a `top` anchor should be sufficient?
