### ISSUE TITLE
Arabic presentation forms U+FBB2...FBC1 and U+FC5E...FC63 should be spacing

### ISSUE THREAD

**Issue by moyogo** [schriftgestalt/GlyphsInfo#22]
GlyphsData.xml currently has U+FBB2...FBC1 and U+FC5E...FC63 with `subCategory="Nonspacing"` but they should be `subCategory="Spacing"`.

See https://www.unicode.org/versions/Unicode12.0.0/ch09.pdf#page=32
![Capture_d_écran_2019-03-25_à_14 00 33](https://user-images.githubusercontent.com/1923747/55004949-132e3580-4fd3-11e9-9e56-85f09b6a97c0.png)

**Comment by schriftgestalt** [comment]
Thanks for the clarification. 

The glyphs are wrongly used as components. I duplicated the entries. Removed the unicodes from the one set and added "Symbol" to the name of the others. 
So `dotabove-ar` (FBB2) becomes `dotaboveSymbol-ar` (FBB2) and `dotabove-ar` (-).

**Comment by moyogo** [comment]
This also needs to happen with the following:
* FC5E shadda_dammatan-ar
* FC5F shadda_kasratan-ar
* FC60 shadda_fatha-ar
* FC61 shadda_damma-ar
* FC62 shadda_kasra-ar
* FC63 shadda_alefabove-ar

The Unicode category of those characters is Lo - "Letter, other", their combining class is 0 - "Spacing, split, enclosing, reordrant, & Tibetan subjoined", and their compatibility decomposition sequences all start with space U+0020.
