### ISSUE TITLE
Files are outdated

### ISSUE THREAD

**Issue by khaledhosny** [schriftgestalt/GlyphsInfo#26]
The files in this repository are outdated, causing fontmake to produce different output (e.g. wrong GDEF glyph classes).

**Comment by schriftgestalt** [comment]
I’ll update the file. Thanks for the reminder.

**Comment by khaledhosny** [comment]
Thanks!

**Comment by schriftgestalt** [comment]
fixed in 8e554a7b59a2d7bd7d1d2bf2a46a794e1b51602c
