### ISSUE TITLE
Separate emoji section?

### ISSUE THREAD

**Issue by davelab6** [schriftgestalt/GlyphsInfo#29]
I suggest to split out emoji from the symbols section. 

Cc @roeln

**Comment by schriftgestalt** [comment]
You mean to move the `Emoji` tag to the category and free up the subCategory. Good idea.

**Comment by schriftgestalt** [comment]
I uploaded the info from Glyphs 3. It contains most of the Emoji in Unicode. I’ll switch the category.

**Comment by davelab6** [comment]
Amazing! Thank you so much

Did you review the universal thirst fork? @kalapi been working on it, I
hope it can go upstream to you

**Comment by schriftgestalt** [comment]
Can you point me to the repo?

**Comment by davelab6** [comment]
https://github.com/universalthirst/UT-GlyphData

**Comment by davelab6** [comment]
@kalapi ah that repo is quite old

**Comment by schriftgestalt** [comment]
that is fixed in the Glyph3 branch
