### ISSUE TITLE
Non-AGL production names for Lao glyphs

### ISSUE THREAD

**Issue by brawer** [schriftgestalt/GlyphsInfo#3]
A few entries in [GlyphData.xml](https://github.com/schriftgestalt/GlyphsInfo/blob/master/GlyphData.xml) have production names that do not comply with the [Adobe Glyph List specification](https://github.com/adobe-type-tools/agl-specification). These problematic glyphs are all for the Lao script. Do you have any background on them? Are these missing from Unicode?

```xml
<glyph name="gha-lao" category="Letter" script="lao" production="laGha_" altNames="laGha" />
<glyph name="cha-lao" category="Letter" script="lao" production="laCha_" altNames="laCha" />
<glyph name="jha-lao" category="Letter" script="lao" production="laJha_" altNames="laJha" />
<glyph name="nya-lao" category="Letter" script="lao" production="laNya_" altNames="laNya" />
<glyph name="tta-lao" category="Letter" script="lao" production="laTta_" altNames="laTta" />
<glyph name="ttha-lao" category="Letter" script="lao" production="laTtha_" altNames="laTtha" />
<glyph name="dda-lao" category="Letter" script="lao" production="laDda_" altNames="laDda" />
<glyph name="ddha-lao" category="Letter" script="lao" production="laDdha_" altNames="laDdha" />
<glyph name="nna-lao" category="Letter" script="lao" production="laNna_" altNames="laNna" />
<glyph name="dha-lao" category="Letter" script="lao" production="laDha_" altNames="laDha" />
<glyph name="bha-lao" category="Letter" script="lao" production="laBha_" altNames="laBha" />
<glyph name="sha-lao" category="Letter" script="lao" production="laSha_" altNames="laSha" />
<glyph name="ssa-lao" category="Letter" script="lao" production="laSsa_" altNames="laSsa" />
<glyph name="lla-lao" category="Letter" script="lao" production="laLla_" altNames="laLla" />
```

**Comment by brawer** [comment]
Likewise, I have trouble generating AGL-compliant production names for the following glyphs which glyphs lack a `production` attribute. For many other glyphs in the data, using `altNames` works fine when a glyph has no `production`, but in the following cases the value for `altNames` cannot be mapped to a Unicode sequence.

```xml
<glyph name="maiEk-lao.small" category="Mark" subCategory="Nonspacing" script="lao" altNames="laMaiEk.calt" />
<glyph name="maiTho-lao.small" category="Mark" subCategory="Nonspacing" script="lao" altNames="laMaiTho.calt" />
<glyph name="maiTi-lao.small" category="Mark" subCategory="Nonspacing" script="lao" altNames="laMaiTi.calt" />
<glyph name="maiCatawa-lao.small" category="Mark" subCategory="Nonspacing" script="lao" altNames="laMaiCatawa.calt" />
<glyph name="karan-lao.small" category="Mark" subCategory="Nonspacing" script="lao" altNames="laKaran.calt" />
<glyph name="niggahita-lao.small" category="Mark" subCategory="Nonspacing" script="lao" altNames="laNiggahita.calt" />
```

**Comment by schriftgestalt** [comment]
>  production="laGha_"

This is a mistake. Names are based of input from Ben Mitchell. I contacted him about his.

**Comment by brawer** [comment]
@mjansche pointed me to the [Thai Wikipedia page about the Lao alphabet](https://th.wikipedia.org/wiki/%E0%B8%AD%E0%B8%B1%E0%B8%81%E0%B8%A9%E0%B8%A3%E0%B8%A5%E0%B8%B2%E0%B8%A7). It seems these extra letters are used in Sanskrit/Pali transliteration (similar to the extended/historical letters in Khmer etc.). But Unicode does not assign codepoints to them. Perhaps we should try to change this.

The Thai Wikipedia has images: [gha](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-gh.png) [cha](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-ch.png) [jha](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-jh.png) [nnya](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-ny.png) [tta](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-T.png) [ttha](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-Th.png) [dda](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-D.png) [ddha](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-Dh.png) [nna](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-N.png) [dha](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-dh.png) [bha](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-bh.png) [sha](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Sanskrit-sh.png) [ssa](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Sanskrit-S.png) [lla](https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C:Lao-Pali-L.png)

**Comment by ohbendy** [comment]
I don't have much information about the non-Unicode Lao characters, other than that they were introduced as a way of representing Pali-Sanskrit words more correctly than is otherwise possible using the current/official Lao alphabet.

There's a bit more :
[here](http://alif-shinobi.blogspot.co.uk/2014/01/indic-lao-script-script-with-pali-and.html)
and 
[here](http://alif-shinobi.blogspot.co.uk/2010/11/lao-traditional-script.html).

I'm hoping to uncover more resources and make a Unicode proposal at some point, but it'll not be for a while unfortunately.

**Comment by brawer** [comment]
FYI, Unicode has accepted a [proposal](http://www.unicode.org/L2/L2017/17106r-lao-for-pali.pdf) for encoding these characters. But it will take a while to flow through the [pipeline](http://unicode.org/alloc/Pipeline.html).

**Comment by ohbendy** [comment]
Are the slots fixed now, or is there any possibility the codepoints could change? If they're not going to change we can add the Pali characters to the Lao XML at any point. I was going to suggest reviewing the Lao XML anyway, as I'm not sure all the categories, subcategories and anchors are correct.

**Comment by brawer** [comment]
No, the codepoint assignments aren’t final yet.

**Comment by schriftgestalt** [comment]
They are properly encoded now.
