### ISSUE TITLE
Arabic dots are missing

### ISSUE THREAD

**Issue by khaledhosny** [schriftgestalt/GlyphsInfo#30]
Glyph names like `dotabove-ar`, `dotbelow-ar`, etc. are missing (while the `Symbol` counterpart are present), which basically breaks building any Arabic fonts with fontmake if these dots are used as combining marks not just as components.

**Comment by schriftgestalt** [comment]
should be fixed with 147a9c62d3c8a0d0d4485d2b41a78ba557ff583b

**Comment by khaledhosny** [comment]
Thanks!
