### ISSUE TITLE
Uptodate-ness compared to Glyphs.app 3.x?

### ISSUE THREAD

**Issue by madig** [schriftgestalt/GlyphsInfo#32]
Hi! Is there anything different in Glyphs.app 3.x that would warrant an update here?

Edit: or actually, which Glyphs.app version was it derived from?

**Comment by schriftgestalt** [comment]
I updated it from Glyphs 3.0.5-3112.

**Comment by madig** [comment]
Hm? According to the blog, 3.0.5 isn't out yet? The data in master is from 14 Sep 2020?

Edit: oh duh, you pushed to a new branch. Which version does the data in master reflect?

**Comment by schriftgestalt** [comment]
That is the latest cutting edge version. Have a look at the glyphs3 branch.

**Comment by madig** [comment]
Yes I saw, thanks :) but what version is the data in the master branch based on?

**Comment by schriftgestalt** [comment]
Not sure. It seems to be Glyphs 2.6.6.

**Comment by justvanrossum** [comment]
Are there any plans to merge the Glyphs3 branche into the main branch? You could tag the current HEAD at master as (say) "glyphs-266", so it is still easily available as a reference.

I would be interested to have this data available as a Python package on PyPI. Would that be useful for others, too? I'd be willing to contribute such a thing, if we can agree on details.

**Comment by anthrotype** [comment]
glyphsLib already comes with a bundled GlyphData.xml resource file which is a mirror of this repository ([manually updated 2 years ago it seems](https://github.com/googlefonts/glyphsLib/blob/main/Lib/glyphsLib/data/GlyphData.xml)) and is available on PyPI. Maybe we can update that copy to match the Glyphs3 xml file as found in the Glyphs3 branch of this repository.

I think @schriftgestalt was working on something related to that in https://github.com/googlefonts/glyphsLib/pull/818 but am not sure what's the status of that is.

If @justvanrossum prefers to have it as a separate pypi project that's also fine by me, glyphsLib can simply require that (which arguably it'd be easier than the current method of duplicating the file from upstream and relying on the developer to do a manual git commit referencing the upstream).

**Comment by justvanrossum** [comment]
> glyphsLib already comes with a bundled GlyphData.xml resource file which is a mirror of this repository

Ah thanks, I didn't realize thay, I'll check it out. May be good enough for my purposes.

**Comment by schriftgestalt** [comment]
Instead of tagging, I tend to leave the branches as the are and keep adding new ones per version.

Finishing the glyphsLib glyphInfo stuff is on the very top of my list.
