### ISSUE TITLE
Add production names for 75 fraction glyphs

### ISSUE THREAD

**Issue by brawer** [schriftgestalt/GlyphsInfo#4]
Currently, [GlyphsData.xml](https://github.com/schriftgestalt/GlyphsInfo/blob/master/GlyphData.xml) does not give production names for 75 fraction glyphs. As far as I can tell, the following production names would comply with the [Adobe Glyph Names specification](https://github.com/adobe-type-tools/agl-specification). Would it make sense to add these production names to GlyphsData.xml?

| Glyph name in Glyphs        | Description           | Proposed production name  |
| ------------- | --------------------- | ----- |
| `twosevenths` | VULGAR FRACTION TWO SEVENTHS | `two_fraction_seven` |
| `threesevenths` | VULGAR FRACTION THREE SEVENTHS | `three_fraction_seven` |
| `foursevenths` | VULGAR FRACTION FOUR SEVENTHS | `four_fraction_seven` |
| `fivesevenths` | VULGAR FRACTION FIVE SEVENTHS | `five_fraction_seven` |
| `sixsevenths` | VULGAR FRACTION SIX SEVENTHS | `six_fraction_seven` |
| `twoninths` | VULGAR FRACTION TWO NINTHS | `two_fraction_nine` |
| `fourninths` | VULGAR FRACTION FOUR NINTHS | `four_fraction_nine` |
| `fiveninths` | VULGAR FRACTION FIVE NINTHS | `five_fraction_nine` |
| `sevenninths` | VULGAR FRACTION SEVEN NINTHS | `seven_fraction_nine` |
| `eightninths` | VULGAR FRACTION EIGHT NINTHS | `eight_fraction_nine` |
| `threetenths` | VULGAR FRACTION THREE TENTHS | `three_fraction_one_zero` |
| `seventenths` | VULGAR FRACTION SEVEN TENTHS | `seven_fraction_one_zero` |
| `ninetenths` | VULGAR FRACTION NINE TENTHS | `nine_fraction_one_zero` |
| `oneelevenths` | VULGAR FRACTION ONE ELEVENTHS | `one_fraction_one_one` |
| `twoelevenths` | VULGAR FRACTION TWO ELEVENTHS | `two_fraction_one_one` |
| `threeelevenths` | VULGAR FRACTION THREE ELEVENTHS | `three_fraction_one_one` |
| `fourelevenths` | VULGAR FRACTION FOUR ELEVENTHS | `four_fraction_one_one` |
| `fiveelevenths` | VULGAR FRACTION FIVE ELEVENTHS | `five_fraction_one_one` |
| `sixelevenths` | VULGAR FRACTION SIX ELEVENTHS | `six_fraction_one_one` |
| `sevenelevenths` | VULGAR FRACTION SEVEN ELEVENTHS | `seven_fraction_one_one` |
| `eightelevenths` | VULGAR FRACTION EIGHT ELEVENTHS | `eight_fraction_one_one` |
| `nineelevenths` | VULGAR FRACTION NINE ELEVENTHS | `nine_fraction_one_one` |
| `tenelevenths` | VULGAR FRACTION TEN ELEVENTHS | `one_zero_fraction_one_one` |
| `onetwelvths` | VULGAR FRACTION ONE TWELVTHS | `one_fraction_one_two` |
| `fivetwelvths` | VULGAR FRACTION FIVE TWELVTHS | `five_fraction_one_two` |
| `seventwelvths` | VULGAR FRACTION SEVEN TWELVTHS | `seven_fraction_one_two` |
| `eleventwelvths` | VULGAR FRACTION ELEVEN TWELVTHS | `one_one_fraction_one_two` |
| `onehundredth` | VULGAR FRACTION ONE HUNDREDTH | `one_fraction_one_zero_zero` |
| `oneovertwo` | NUT FRACTION ONE OVER TWO | `one_fraction_two.afrc` |
| `oneoverthree` | NUT FRACTION ONE OVER THREE | `one_fraction_three.afrc` |
| `twooverthree` | NUT FRACTION TWO OVER THREE | `two_fraction_three.afrc` |
| `zerooverthree` | NUT FRACTION ZERO OVER THREE | `zero_fraction_three.afrc` |
| `oneoverfour` | NUT FRACTION ONE OVER FOUR | `one_fraction_four.afrc` |
| `threeoverfour` | NUT FRACTION THREE OVER FOUR | `three_fraction_four.afrc` |
| `fouroverfive` | NUT FRACTION FOUR OVER FIVE | `four_fraction_five.afrc` |
| `oneoverfive` | NUT FRACTION ONE OVER FIVE | `one_fraction_five.afrc` |
| `threeoverfive` | NUT FRACTION THREE OVER FIVE | `three_fraction_five.afrc` |
| `twooverfive` | NUT FRACTION TWO OVER FIVE | `two_fraction_five.afrc` |
| `fiveoversix` | NUT FRACTION FIVE OVER SIX | `five_fraction_six.afrc` |
| `oneoversix` | NUT FRACTION ONE OVER SIX | `one_fraction_six.afrc` |
| `fiveoverseven` | NUT FRACTION FIVE OVER SEVEN | `five_fraction_seven.afrc` |
| `fouroverseven` | NUT FRACTION FOUR OVER SEVEN | `four_fraction_seven.afrc` |
| `oneoverseven` | NUT FRACTION ONE OVER SEVEN | `one_fraction_seven.afrc` |
| `sixoverseven` | NUT FRACTION SIX OVER SEVEN | `six_fraction_seven.afrc` |
| `threeoverseven` | NUT FRACTION THREE OVER SEVEN | `three_fraction_seven.afrc` |
| `twooverseven` | NUT FRACTION TWO OVER SEVEN | `two_fraction_seven.afrc` |
| `fiveovereight` | NUT FRACTION FIVE OVER EIGHT | `five_fraction_eight.afrc` |
| `oneovereight` | NUT FRACTION ONE OVER EIGHT | `one_fraction_eight.afrc` |
| `sevenovereight` | NUT FRACTION SEVEN OVER EIGHT | `seven_fraction_eight.afrc` |
| `threeovereight` | NUT FRACTION THREE OVER EIGHT | `three_fraction_eight.afrc` |
| `eightovernine` | NUT FRACTION EIGHT OVER NINE | `eight_fraction_nine.afrc` |
| `fiveovernine` | NUT FRACTION FIVE OVER NINE | `five_fraction_nine.afrc` |
| `fourovernine` | NUT FRACTION FOUR OVER NINE | `four_fraction_nine.afrc` |
| `oneovernine` | NUT FRACTION ONE OVER NINE | `one_fraction_nine.afrc` |
| `sevenovernine` | NUT FRACTION SEVEN OVER NINE | `seven_fraction_nine.afrc` |
| `twoovernine` | NUT FRACTION TWO OVER NINE | `two_fraction_nine.afrc` |
| `nineoverten` | NUT FRACTION NINE OVER TEN | `nine_fraction_one_zero.afrc` |
| `oneoverten` | NUT FRACTION ONE OVER TEN | `one_fraction_one_zero.afrc` |
| `sevenoverten` | NUT FRACTION SEVEN OVER TEN | `seven_fraction_one_zero.afrc` |
| `threeoverten` | NUT FRACTION THREE OVER TEN | `three_fraction_one_zero.afrc` |
| `eightovereleven` | NUT FRACTION EIGHT OVER ELEVEN | `eight_fraction_one_one.afrc` |
| `fiveovereleven` | NUT FRACTION FIVE OVER ELEVEN | `five_fraction_one_one.afrc` |
| `fourovereleven` | NUT FRACTION FOUR OVER ELEVEN | `four_fraction_one_one.afrc` |
| `nineovereleven` | NUT FRACTION NINE OVER ELEVEN | `nine_fraction_one_one.afrc` |
| `oneovereleven` | NUT FRACTION ONE OVER ELEVEN | `one_fraction_one_one.afrc` |
| `sevenovereleven` | NUT FRACTION SEVEN OVER ELEVEN | `seven_fraction_one_one.afrc` |
| `sixovereleven` | NUT FRACTION SIX OVER ELEVEN | `six_fraction_one_one.afrc` |
| `tenovereleven` | NUT FRACTION TEN OVER ELEVEN | `one_zero_fraction_one_one.afrc` |
| `threeovereleven` | NUT FRACTION THREE OVER ELEVEN | `three_fraction_one_one.afrc` |
| `twoovereleven` | NUT FRACTION TWO OVER ELEVEN | `two_fraction_one_one.afrc` |
| `elevenovertwelve` | NUT FRACTION ELEVEN OVER TWELVE | `one_one_fraction_one_two.afrc` |
| `fiveovertwelve` | NUT FRACTION FIVE OVER TWELVE | `five_fraction_one_two.afrc` |
| `oneovertwelve` | NUT FRACTION ONE OVER TWELVE | `one_fraction_one_two.afrc` |
| `sevenovertwelve` | NUT FRACTION SEVEN OVER TWELVE | `seven_fraction_one_two.afrc` |
| `oneoveronehundred` | NUT FRACTION ONE OVER ONEHUNDRED | `one_fraction_one_zero_zero.afrc` |

**Comment by schriftgestalt** [comment]
My internal version has those names already. I’ll update the public file, soon.

**Comment by brawer** [comment]
Thank you, much appreciated!

**Comment by schriftgestalt** [comment]
I just pushed the latest data.

**Comment by brawer** [comment]
For the following 46 fraction glyphs, there’s still no production name:

```xml
<glyph name="oneoverthree" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER three" />
<glyph name="twooverthree" category="Number" subCategory="Fraction" description="NUT FRACTION two OVER three" />
<glyph name="zerooverthree" category="Number" subCategory="Fraction" description="NUT FRACTION zero OVER three" />
<glyph name="oneoverfour" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER four" />
<glyph name="threeoverfour" category="Number" subCategory="Fraction" description="NUT FRACTION three OVER four" />
<glyph name="fouroverfive" category="Number" subCategory="Fraction" description="NUT FRACTION four OVER five" />
<glyph name="oneoverfive" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER five" />
<glyph name="threeoverfive" category="Number" subCategory="Fraction" description="NUT FRACTION three OVER five" />
<glyph name="twooverfive" category="Number" subCategory="Fraction" description="NUT FRACTION two OVER five" />
<glyph name="fiveoversix" category="Number" subCategory="Fraction" description="NUT FRACTION five OVER six" />
<glyph name="oneoversix" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER six" />
<glyph name="fiveoverseven" category="Number" subCategory="Fraction" description="NUT FRACTION five OVER seven" />
<glyph name="fouroverseven" category="Number" subCategory="Fraction" description="NUT FRACTION four OVER seven" />
<glyph name="oneoverseven" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER seven" />
<glyph name="sixoverseven" category="Number" subCategory="Fraction" description="NUT FRACTION six OVER seven" />
<glyph name="threeoverseven" category="Number" subCategory="Fraction" description="NUT FRACTION three OVER seven" />
<glyph name="twooverseven" category="Number" subCategory="Fraction" description="NUT FRACTION two OVER seven" />
<glyph name="fiveovereight" category="Number" subCategory="Fraction" description="NUT FRACTION five OVER eight" />
<glyph name="oneovereight" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER eight" />
<glyph name="sevenovereight" category="Number" subCategory="Fraction" description="NUT FRACTION seven OVER eight" />
<glyph name="threeovereight" category="Number" subCategory="Fraction" description="NUT FRACTION three OVER eight" />
<glyph name="eightovernine" category="Number" subCategory="Fraction" description="NUT FRACTION eight OVER nine" />
<glyph name="fiveovernine" category="Number" subCategory="Fraction" description="NUT FRACTION five OVER nine" />
<glyph name="fourovernine" category="Number" subCategory="Fraction" description="NUT FRACTION four OVER nine" />
<glyph name="oneovernine" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER nine" />
<glyph name="sevenovernine" category="Number" subCategory="Fraction" description="NUT FRACTION seven OVER nine" />
<glyph name="twoovernine" category="Number" subCategory="Fraction" description="NUT FRACTION two OVER nine" />
<glyph name="nineoverten" category="Number" subCategory="Fraction" description="NUT FRACTION nine OVER ten" />
<glyph name="oneoverten" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER ten" />
<glyph name="sevenoverten" category="Number" subCategory="Fraction" description="NUT FRACTION seven OVER ten" />
<glyph name="threeoverten" category="Number" subCategory="Fraction" description="NUT FRACTION three OVER ten" />
<glyph name="eightovereleven" category="Number" subCategory="Fraction" description="NUT FRACTION eight OVER eleven" />
<glyph name="fiveovereleven" category="Number" subCategory="Fraction" description="NUT FRACTION five OVER eleven" />
<glyph name="fourovereleven" category="Number" subCategory="Fraction" description="NUT FRACTION four OVER eleven" />
<glyph name="nineovereleven" category="Number" subCategory="Fraction" description="NUT FRACTION nine OVER eleven" />
<glyph name="oneovereleven" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER eleven" />
<glyph name="sevenovereleven" category="Number" subCategory="Fraction" description="NUT FRACTION seven OVER eleven" />
<glyph name="sixovereleven" category="Number" subCategory="Fraction" description="NUT FRACTION six OVER eleven" />
<glyph name="tenovereleven" category="Number" subCategory="Fraction" description="NUT FRACTION ten OVER eleven" />
<glyph name="threeovereleven" category="Number" subCategory="Fraction" description="NUT FRACTION three OVER eleven" />
<glyph name="twoovereleven" category="Number" subCategory="Fraction" description="NUT FRACTION two OVER eleven" />
<glyph name="elevenovertwelve" category="Number" subCategory="Fraction" description="NUT FRACTION eleven OVER twelve" />
<glyph name="fiveovertwelve" category="Number" subCategory="Fraction" description="NUT FRACTION five OVER twelve" />
<glyph name="oneovertwelve" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER twelve" />
<glyph name="sevenovertwelve" category="Number" subCategory="Fraction" description="NUT FRACTION seven OVER twelve" />
<glyph name="oneoveronehundred" category="Number" subCategory="Fraction" description="NUT FRACTION one OVER onehundred" />
```

**Comment by schriftgestalt** [comment]
fixed.
