### ISSUE TITLE
Inconsistent casing for U+231D TOP RIGHT CORNER

### ISSUE THREAD

**Issue by devosb** [schriftgestalt/GlyphsInfo#40]
Consider four characters in the database

- U+231C TOP LEFT CORNER
- U+231D TOP RIGHT CORNER
- U+231E BOTTOM LEFT CORNER
- U+231F BOTTOM RIGHT CORNER

They have corresponding names in the database of

- topLeftCorner
- topRightcorner
- bottomLeftCorner
- bottomRightCorner

To be consistent, U+231D needs to be named topRightCorner (the `c` needs to be uppercase)

**Comment by schriftgestalt** [comment]
fixed
