### ISSUE TITLE
Wrong prefix in production names for non-BMP glyphs

### ISSUE THREAD

**Issue by brawer** [schriftgestalt/GlyphsInfo#7]
According to the [AGL specification](https://github.com/adobe-type-tools/agl-specification#2-the-mapping), glyph names that start with `uni` must be followed by a sequence of hex digits whose length is a multiple of four. However, in the current GlyphData.xml file, production names sometimes have `uni` followed by five digits. Instead, glyphs whose codepoint is outside the Basic Multilingual Plane should use `u` as their prefix. For example, the `production` field of `Gscript-math` should be `u1D4A2` instead of `uni1D4A2`.

```xml
<glyph unicode="1D4A2" name="Gscript-math" category="Letter" subCategory="Uppercase"
    script="math" production="uni1D4A2" description="MATHEMATICAL SCRIPT CAPITAL G" />
```

**Comment by schriftgestalt** [comment]
fixed
