### ISSUE TITLE
Production names for commaaccent glyphs

### ISSUE THREAD

**Issue by brawer** [schriftgestalt/GlyphsInfo#9]
In new fonts, Adobe [recommends](https://github.com/adobe-type-tools/agl-aglfn/blob/master/aglfn.txt#L81) to use `uniXXXX` instead of `Xcommaaccent`. Would it make sense to add the following `production` names to GlyphsData.xml?

| Character | Glyphs name | Proposed production name |
| ---------- | ------------- | --------------------------- |
| Ģ | Gcommaaccent | uni0122|
| Ķ | Kcommaaccent | uni0136|
| Ļ | Lcommaaccent | uni013B|
| Ņ | Ncommaaccent | uni0145|
| Ŗ | Rcommaaccent | uni0156|
| Ș | Scommaaccent | uni0218|
| ģ | gcommaaccent | uni0123|
| ķ | kcommaaccent | uni0137|
| ļ | lcommaaccent | uni013C|
| ņ | ncommaaccent | uni0146|
| ŗ | rcommaaccent | uni0157|
| ș | scommaaccent | uni0219|

**Comment by schriftgestalt** [comment]
Changed it in my list. Will put it in the next bigger release.

**Comment by moyogo** [comment]
This can be closed.
